root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
full_bin = "./tmp/server -p 8080"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", ".git", ".gocache", ".gomodcache"]
include_dir = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "build-errors.log"
delay = 400
stop_on_error = true
send_interrupt = false
kill_delay = "0s"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = true

[misc]
clean_on_exit = true
